=== musichopin/Derek-Banas_XML/New folder (5)/tvshow5.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT tvshow (show)+>
<!ELEMENT show (name, release, network+, description, actors, poster?, viewers?, (end_date | next_episode))>

<!-- You can use an entity to create shortcuts in your dtd files -->
<!-- An entity just replaces a code like < becomes less than -->
<!-- You can pull the data that will replace the &code; from the dtd
	or from an outside file -->
	
<!-- There are 5 entities built into xml & &apost; > < " -->
	
<!-- This is called a parameter entity. It is a shortcut that is
	used inside of a dtd file. It just replaces all occurrences of
	%pd; with (#PCDATA) -->

<!ENTITY % pd "(#PCDATA)">

<!ELEMENT name %pd;> 
<!ATTLIST name id_code ID #REQUIRED>

<!ELEMENT release (#PCDATA)> 

<!ELEMENT network (#PCDATA)> 
<!ATTLIST network country CDATA #REQUIRED>

<!ELEMENT description (#PCDATA)>

<!ELEMENT actors (actor)*>
<!ELEMENT actor (real_name, character)>
<!ELEMENT real_name (#PCDATA)>
<!ELEMENT character (#PCDATA)>
<!ATTLIST character profession CDATA #IMPLIED>

<!-- You can also replace a parameter entity with data 
	from other files -->

<!--
<!ELEMENT poster EMPTY> 
<!ATTLIST poster href CDATA #IMPLIED>
<!ATTLIST poster width CDATA #IMPLIED>
<!ATTLIST poster height CDATA #IMPLIED>
<!ATTLIST poster show_id IDREF #IMPLIED>
-->

<!-- %poster; will be replaced with the data in tvposter5.ent -->

<!ENTITY % poster SYSTEM "tvshows5.ent">

%poster;

<!ELEMENT viewers (#PCDATA)>
<!ATTLIST viewers units (thousand | million) #IMPLIED>

<!ELEMENT end_date (#PCDATA)>
<!ELEMENT next_episode (#PCDATA)>

<!-- You define a general entity in a dtd file that can be used 
	in the xml file -->
	
<!-- In the xml file type &great; to get the phrase to show up -->

<!ENTITY great "This show was great!">

<!-- In the xml file type &tv_disclaimer; to get the text 
	stored in tvshow5.ent to show up -->

<!ENTITY tv_disclaimer SYSTEM "tvshowsdis.ent">

=== musichopin/Derek-Banas_XML/New folder (5)/tvshow5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tvshow SYSTEM "tvshow5.dtd">
<?xml-stylesheet type="text/xsl" href="tvshow5.xsl" ?>
<tvshow>
  <show>
    <name id_code="show_001">Life On Mars</name>
    <release>2008</release>
    <network country="US">ABC</network>
    <description>The series tells the story of New York City police detective Sam Tyler. &great; &tv_disclaimer;</description>
    <actors>
		<actor>
			<real_name>Jason O'Mara</real_name>
			<character profession="Detective">Sam Tyler</character>
		</actor>
		<actor>
			<real_name>Michael Imperioli</real_name>
			<character profession="Detective">Ray Carling</character>	
		</actor>
	</actors>
	<poster href="http://ia.media-imdb.com/images/M/MV5BMTM4MDg2NTk1OF5BMl5BanBnXkFtZTcwNzI4OTY5MQ@@._V1._SY317_CR12,0,214,317_.jpg" width="214" height="317" />
    <viewers units="million">7.82</viewers>
    <end_date>2009</end_date>
  </show>
  
  <show>
    <name id_code="show_002">Life On Mars</name>
    <release>2006</release>
    <network country="UK">BBC</network>
    <description>The series combines elements of science fiction and police procedural. &great; &tv_disclaimer;</description>
    <actors>
		<actor>
			<real_name>John Simm</real_name>
			<character profession="Detective">Sam Tyler</character>
		</actor>
		<actor>
			<real_name>Philip Glenister</real_name>
			<character profession="Detective">Gene Hunt</character>	
		</actor>
	</actors>
	<poster href="http://ia.media-imdb.com/images/M/MV5BMTQxNzc5MjQwNF5BMl5BanBnXkFtZTcwMjU3Njc4Mg@@._V1._SY317_CR8,0,214,317_.jpg" width="214" height="317" />
    <viewers units="million">6.8</viewers>
    <end_date>2007</end_date>
  </show>
</tvshow>
